# Generated by Django 5.1.6 on 2025-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='dosponible',
            new_name='disponible',
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('no_ficcion', 'No ficción'), ('fantasia', 'Fantasía'), ('ciencia', 'Ciencia'), ('historia', 'Historia')], max_length=100),
        ),
    ]
